config/routes.rb
Rails.application.routes.draw do

  resources :orders, only: %i[index destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  scope path: '/api', as: :api do
    scope :v1 do
      resources :orders, controller: 'api/v1/orders'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/drivetest.rb
require 'google_drive'
require 'pry'
# config.jsonを読み込んでセッションを確立
  session = GoogleDrive::Session.from_config("config.json")

  # スプレッドシートをURLで取得
  sp = session.spreadsheet_by_url("https://docs.google.com/spreadsheets/d/1-yzjw6y0P_I-kyxg6qzyhC94DH7BTE5e17FIpg89S4E/edit#gid=0")

  # "シート1"という名前のワークシートを取得
  ws = sp.worksheet_by_title('シート1')
  binding.pry
  # セルを指定して値を更新　インデックスの基準は1
  ws[1, 1] = "foo" # セルA2
  ws[1, 2] = "bar" # セルB2

  # saveで変更を保存、実際にスプレッドシートに反映させる
  ws.save

app/models/order.rb
class Order < ApplicationRecord
end

app/controllers/api/v1/orders_controller.rb
class Api::V1::OrdersController < ApplicationController

  def create
    binding.pry
    order = Order.new(order_params)

    if order.save
      render json: order, status: 200
    else
      render json: { errors: order.errors.full_messages[0] }, status: :unprocessable_entity
    end
  end


  private

  def order_params
    params.require(:order).permit(:order_name, :order_amount)
  end



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session, if: ->{request.format.json?}
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order , only: [:destroy]
  def index
    @order = Order.all
  end




  def destroy
  @order.destroy
  redirect_to(orders_path)
  end

  def set_order
    @order = Order.find_by(params[:id])
  end
end

app/helpers/api/v1/orders_helper.rb
module Api::V1::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand navbar-brand-center" href="/">Clova Waiter</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Menu <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Clova Waiter</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="wrapper">
        <%= render 'layouts/header' %>
        <% flash.each do |name, msg| %>
          <div class="alert alert-<%= name == "notice" ? "success" : "error" %>">
            <a class="close" data-dismiss="alert">×</a> <!-- アラートダイアログに×ボタンをつける -->
            <%= msg %>
          </div>
        <% end %>
        <%= yield %>
        </div>
      </body>
</html>

app/views/orders/index.html.erb
<style media="screen">
  font-family: arai, sans-self;
</style>
<h1>オーダー</h1>
<% @order.each do |o| %>
  <p>商品名：<%=o.order_name%></p>
  <p>個数：<%=o.order_amount%></p>
  <p>注文時間：<%=o.created_at%></p>
  <%= link_to "完了", order_path(o.id), method: :delete %>
<%end%>